import 'dart:io';
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:supabase_flutter/supabase_flutter.dart';
import '../home/home_screen.dart'; 
import 'report_detail_screen.dart';

/// Renders a tailored feed of reports based on dynamic query parameters.
///
/// Consumes the payload generated by [FilterScreen] to construct and execute 
/// a complex, multi-relational PostgREST query against the Supabase backend.
class ResultadosBusquedaScreen extends StatefulWidget {
  /// A dictionary containing the active search constraints (e.g., text, foreign keys, enums).
  final Map<String, dynamic> filtros;

  const ResultadosBusquedaScreen({super.key, required this.filtros});

  @override
  State<ResultadosBusquedaScreen> createState() => _ResultadosBusquedaScreenState();
}

class _ResultadosBusquedaScreenState extends State<ResultadosBusquedaScreen> {
  List<Map<String, dynamic>> _reportes = [];
  bool _isLoading = true;

  /// Pagination configuration parameters.
  int _rangoInicio = 0;
  final int _cantidadPorPagina = 15; 
  bool _hayMasDatos = true;
  bool _cargandoMas = false;

  final ScrollController _scrollController = ScrollController();

  @override
  void initState() {
    super.initState();
    _cargarResultados();
  }

  @override
  void dispose() {
    _scrollController.dispose();
    super.dispose();
  }

  /// Smoothly animates the list back to the top offset.
  /// 
  /// Bound to hardware keyboard shortcuts (ArrowUp / Home) via [CallbackShortcuts].
  void _scrollToTop() {
    if (_scrollController.hasClients) {
      _scrollController.animateTo(
        0.0, 
        duration: const Duration(milliseconds: 600), 
        curve: Curves.easeOutCubic,
      );
    }
  }

  /// Dynamic Query Builder (PostgREST).
  ///
  /// Evaluates the [filtros] payload to procedurally generate a Supabase query.
  /// Dynamically alters the Select string to enforce strict `!inner` joins 
  /// only when deep relational filtering (like `carreraId`) is required, 
  /// optimizing query execution time on the Postgres database.
  PostgrestFilterBuilder<List<Map<String, dynamic>>> _construirConsultaSupabase() {
    final supabase = Supabase.instance.client;
    final carreraId = widget.filtros['carreraId'];
    
    // Default projection for standard filtering.
    String stringSelect = '''
      id, titulo, estado, evidencia_url, reaccion_count, categoria_id,
      cat_categorias (id, nombre, icono, color),
      perfiles!inner (nombre, estudiantes(numero_control, carrera_id)),
      reporte_ubicaciones!inner (lugar_id, cat_lugares(id, nombre))
    ''';

    // Strict projection: Forces an inner join on the 'estudiantes' table 
    // to guarantee we only fetch reports from users belonging to the target major.
    if (carreraId != null) {
      stringSelect = '''
        id, titulo, estado, evidencia_url, reaccion_count, categoria_id,
        cat_categorias (id, nombre, icono, color),
        perfiles!inner (nombre, estudiantes!inner(numero_control, carrera_id)),
        reporte_ubicaciones!inner (lugar_id, cat_lugares(id, nombre))
      ''';
    }

    var query = supabase.from('reportes').select(stringSelect);

    // Enforce base visibility constraint.
    query = query.eq('visible', true); 

    // --- Dynamic Filter Appending ---
    final titulo = widget.filtros['titulo']?.toString().trim() ?? '';
    if (titulo.isNotEmpty) query = query.ilike('titulo', '%$titulo%');

    final categoriaId = widget.filtros['categoriaId'];
    if (categoriaId != null) query = query.eq('categoria_id', categoriaId);

    // Deep relational filter.
    if (carreraId != null) {
      query = query.filter('perfiles.estudiantes.carrera_id', 'eq', carreraId);
    }

    final estadoFiltro = widget.filtros['estado'] ?? 'todos';
    if (estadoFiltro != 'todos') query = query.eq('estado', estadoFiltro);

    final lugarId = widget.filtros['lugarId'];
    if (lugarId != null) query = query.eq('reporte_ubicaciones.lugar_id', lugarId);

    final usuario = widget.filtros['usuario']?.toString().trim() ?? '';
    if (usuario.isNotEmpty) query = query.ilike('perfiles.nombre', '%$usuario%');

    return query;
  }

  /// Executes the compiled query and initializes the first pagination chunk.
  Future<void> _cargarResultados() async {
    setState(() => _isLoading = true);
    _rangoInicio = 0;
    _hayMasDatos = true;

    try {
      var queryBase = _construirConsultaSupabase();
      PostgrestTransformBuilder<List<Map<String, dynamic>>> queryOrdenada;
      
      // Apply user-defined sorting criteria prior to range execution.
      final orden = widget.filtros['ordenReacciones'] ?? 'recientes';
      if (orden == 'desc') {
        queryOrdenada = queryBase.order('reaccion_count', ascending: false).order('id', ascending: false);
      } else if (orden == 'asc') {
        queryOrdenada = queryBase.order('reaccion_count', ascending: true).order('id', ascending: false);
      } else {
        queryOrdenada = queryBase.order('id', ascending: false);
      }

      final response = await queryOrdenada.range(_rangoInicio, _rangoInicio + _cantidadPorPagina - 1);

      if (mounted) {
        setState(() {
          _reportes = List<Map<String, dynamic>>.from(response);
          _isLoading = false;
          if (response.length < _cantidadPorPagina) _hayMasDatos = false;
        });
      }
    } catch (e) {
      if (mounted) setState(() => _isLoading = false);
    }
  }

  /// Fetches the subsequent payload of filtered reports (Pagination).
  Future<void> _cargarMasResultados() async {
    if (_cargandoMas || !_hayMasDatos) return;

    setState(() => _cargandoMas = true);
    _rangoInicio += _cantidadPorPagina;

    try {
      var queryBase = _construirConsultaSupabase();
      PostgrestTransformBuilder<List<Map<String, dynamic>>> queryOrdenada;
      
      final orden = widget.filtros['ordenReacciones'] ?? 'recientes';
      if (orden == 'desc') {
        queryOrdenada = queryBase.order('reaccion_count', ascending: false).order('id', ascending: false);
      } else if (orden == 'asc') {
        queryOrdenada = queryBase.order('reaccion_count', ascending: true).order('id', ascending: false);
      } else {
        queryOrdenada = queryBase.order('id', ascending: false);
      }

      final response = await queryOrdenada.range(_rangoInicio, _rangoInicio + _cantidadPorPagina - 1);

      if (mounted) {
        setState(() {
          if (response.isEmpty) {
            _hayMasDatos = false; 
          } else {
            _reportes.addAll(List<Map<String, dynamic>>.from(response));
            if (response.length < _cantidadPorPagina) _hayMasDatos = false;
          }
          _cargandoMas = false; 
        });
      }
    } catch (e) {
      if (mounted) setState(() => _cargandoMas = false);
    }
  }

  @override
  Widget build(BuildContext context) {
    // Hardware evaluation to apply correct OS-level modifier keys.
    final bool isMac = !kIsWeb && Platform.isMacOS;

    return CallbackShortcuts(
      bindings: {
        SingleActivator(LogicalKeyboardKey.arrowUp, control: !isMac, meta: isMac): _scrollToTop,
        const SingleActivator(LogicalKeyboardKey.home): _scrollToTop,
      },
      child: Focus(
        autofocus: true,
        child: Scaffold(
          appBar: AppBar(
            title: GestureDetector(
              onTap: _scrollToTop,
              child: const Text("Resultados de Búsqueda"),
            ),
            backgroundColor: const Color(0xFF800000),
            foregroundColor: Colors.white,
          ),
          body: _isLoading
              ? const Center(child: CircularProgressIndicator(color: Color(0xFF800000)))
              : _reportes.isEmpty
                  ? const Center(
                      child: Column(
                        mainAxisAlignment: MainAxisAlignment.center,
                        children: [
                          Icon(Icons.search_off, size: 80, color: Colors.grey),
                          SizedBox(height: 16),
                          Text("No se encontraron reportes con estos filtros.", style: TextStyle(color: Colors.grey, fontSize: 16)),
                        ],
                      ),
                    )
                  : ListView.builder(
                      controller: _scrollController, 
                      padding: const EdgeInsets.all(12),
                      itemCount: _reportes.length + 1, 
                      itemBuilder: (context, index) {
                        
                        // Render pagination trigger at the end of the list.
                        if (index == _reportes.length) {
                          if (!_hayMasDatos) return const SizedBox.shrink();
                          
                          return Padding(
                            padding: const EdgeInsets.symmetric(vertical: 20),
                            child: _cargandoMas
                              ? const Center(child: CircularProgressIndicator(color: Color(0xFF800000)))
                              : Center(
                                  child: OutlinedButton.icon(
                                    onPressed: _cargarMasResultados,
                                    icon: const Icon(Icons.add, color: Color(0xFF800000)), 
                                    label: const Text("Cargar más resultados", style: TextStyle(color: Color(0xFF800000))),
                                    style: OutlinedButton.styleFrom(side: const BorderSide(color: Color(0xFF800000))),
                                  ),
                                ),
                          );
                        }

                        return TarjetaReporteOptimizada(
                          reporte: _reportes[index],
                          onTap: () async {
                            // Await the modal pop to automatically refresh the feed 
                            // in case the user edited or deleted the report inside.
                            await Navigator.push(
                              context,
                              MaterialPageRoute(builder: (context) => ReportDetailScreen(reporteId: _reportes[index]['id'])),
                            );
                            _cargarResultados(); 
                          },
                        );
                      },
                    ),
        ),
      ),
    );
  }
}